name: High Performance Enricher build
on:
    workflow_dispatch:
jobs:
    build:
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v4
        - run: ./gradlew clean build
        - uses: actions/upload-artifact@v4
          with:
            path: build/libs/high-performance-enricher-0.0.1-SNAPSHOT.jar
            name: high-performance-enricher
